### ISSUE TITLE
How to interpret the weight matrix a

### ISSUE THREAD

**Issue by WUZHExl** [llrs/RGCCA#33]
1.Whether the values of different dimensions of the same variable in the matrix are comparable
2.Negative value

**Comment by llrs** [comment]
Hi, I am not the author of RGCCA, just a user. If you want you can write to the authors on [their repository](https://github.com/rgcca-factory/RGCCA/). They might help you better 

1. If I remember correctly, each dimension is scaled and normalized so they are not comparable across dimensions.
2. Negative values indicate that the variable contributes towards the other sign of the axis. Depending on the different variables or the block, the interpretation could change, for instance it could be that a variable is not causing inflammation but preventing it while others are related to inflammation.

**Comment by WUZHExl** [comment]
Thank you for your reply. It helped me a lot.

Could you please ask me two more questions:

1. Weights of different blocks on clustering results. According to the value of ncomp, I convert the weight of the block into equal ratio, but I am not sure whether it is accurate.

2. Weights of different variables in the same block on results. If the matrix contains more than one principal component, how to calculate？

**Comment by llrs** [comment]
I can help you with two more questions, but I don't understand your first question. Could you share some example about how you calculate those equal ratios? ncomp is a parameter you set, and setting 5 or 999 won't (shouldn't) change the weights for the first 5 dimensions. 

A matrix with n variables, has n-1 principal components. If you want more dimensions you just need to increase the ncomp value.

**Comment by WUZHExl** [comment]
Suppose there are three blocks A, B, and C, whose sizes are nxp1, nxp2, and nxp3 respectively, and ncomp=c(6,3,1).

1. Therefore, I think the influence weights of the three blocks on the clustering results are 60%, 30% and 10% respectively. Is this reasonable?

2. Suppose I need to calculate the contribution of variable x of block A to the clustering result.
The method I use is this
Contribution =sum(abs(weight sum of variable a in 6 dimensions)/sum(abs(sum of all values of all variables in block A in 6 dimensions)).
 Is this reasonable?

**Comment by llrs** [comment]
1. This is not what the code and the documentations says: ncomp "contains the numbers of components for each block", not the weight of each block. To have the weight for each block you need to set that up in C, the design matrix. Even then the weight is for the relationship between two blocks, not the weight of a block in the overall design. 

```r
C <- matrix(0, ncol = 3, nrow = 3)
C[1, 2] <- 0.6 
C[2, 1] <- 0.6 
C[1, 3] <- 0.1
C[3, 1] <- 0.1
C[2, 3] <- 0.2
C[3, 2] <- 0.2
colnames(C) <- LETTERS[1:3]
rownames(C) <- LETTERS[1:3]
C
```

In this design the matrix A is related to B by 0.6 and to C by 0.2 but B and C are related a 0.2.
As you can see here the weight of a specific block doesn't need to add up to 1, but you could make it so that they were up to 1 and the overall design up to the number of blocks it has.  
Remember that the weight is used when calculating the best fit for the data between the two pairs of vectors comming from each block.

2. Yes you could calculate that with something like this:

```r
A_weights <- rgcca_output$a$A
a_contribution_per_dimension <- abs(A_weights["variable a", ])/colSums(abs(A_weights))
a_contribution_across_dimensions <- sum(a_contribution_per_dimension) 
```
But, why would you want to calculate the contribution of a variable across different dimensions?

Maybe I am misunderstanding your question: How do you define the clustering in your example? The output of such analysis would be a 10 dimensions results with no label for each sample. Samples could end up in 10 or 2 "clusters" in this 6-dimensional output (but I would recommend to simply use `ncomp = rep(6, 3)` to have all the dimension reductions of all the blocks [Computationally it would be the same but simply RGCCA would return all the output calculated]). You need another method to group the different samples after the output of RGCCA imho.

**Comment by WUZHExl** [comment]
I am using RGCCA to integrate multi-modal data and use the integration results for clustering, in which rows are genes and columns are samples.

I hope to get a list of genes by calculating contribution, so as to conduct relevant downstream analysis.

Therefore, I want to know: 
1. The contribution of a variable (gene) to clustering on a block;
2. And the contribution of this variable to clustering as a whole;

Some genes may exist in different blocks, so it is necessary to obtain the contribution degree of different blocks to clustering. For example, gene x exists in block A and B, and its contribution degree is 0.6 and 0.3 respectively. The contribution degree of A and B to clustering is 0.4 and 0.6 respectively, so the contribution degree of gene A to clustering is 0.6x0.4+0.6x0.3.

When ncomp=c(6,3,1), the matrix used for clustering is 10-dimensional, where each block has 6,3, and 1 dimension respectively.
So I thought the contribution per block was 0.6, 0.3, 0.1.

However, I don't quite understand the calculation using design matrix C you mentioned.
If the correlation coefficient between matrix A and B is 0.6, and the correlation coefficient between matrix A and C is 0.2, but the correlation coefficient between B and C is 0.2, then how should the contribution of matrix A to clustering be expressed?

**Comment by llrs** [comment]
Thanks for providing the background of your analysis. My opinion is that RGCCA is not really a clustering method, but a dimensional reduction method (Canonical correlations where designed to see if different raters agreed on the same variables not to group raters in clusters). If you use the output of RGCCA for a clustering using a different method is up to you when selecting that method to know how does each variable contribute. But for RGCCA dimension reduction, the contribution of a variable is the weight, and the contribution of a block in the output is controlled by the C matrix.

If you use another method where you have 6 columns of block A and you don't use any weight, then yes in principle, check with the method you use, block A is contributing 60% of your columns to your clustering, but not to the dimensional reduction method used to get those 6 columns.

**Comment by WUZHExl** [comment]
A block's contribution to the output is controlled by a C matrix？

Doesn't matrix C just indicate whether the blocks are connected or not?

If block A has a relationship of 0.6 with B and 0.2 with C, but B has a relationship of 0.2 with C.

So how do we calculate the contribution of block A？

**Comment by llrs** [comment]
No, if you read the formula of the RGCCA in [Tenenhaus  2011](https://doi.org/10.1007/s11336-011-9206-8) and as implemented in the code, where C defines the weight of the connection:

![RGCCA_formula](https://user-images.githubusercontent.com/6818218/210236774-fbce6aa2-9d05-4671-9375-c22c170f0b3d.PNG) 
Here c_jk is the value in the matrix C for row j and column k. 

To calculate the contribution of block A to the overall output of RGCCA you can use the average Variance Expression (AVE) score provided by `rgcca `and `sgcca` (I recommend the later as you are analyzing gene expression data).
The AVE provides an estimation between 0 and 1 for the contribution of each block to the model (the higher, the more it contributes). See `sgcca_output$AVE$AVE_X` for the importance of each block in each dimension calculated and `sgcca_output$AVE$AVE_inner` for how well the design fits to the data.

I'll close the issue as this  is not a question about the implementation of the package but some doubts you have. Perhaps you should think more carefully how you use RGCCA and ask a statistician you trust as I might be wrong. I hope you perform an accurate and good analysis.

**Comment by WUZHExl** [comment]
Thank you for your reply. It helped me a lot.

**Comment by llrs** [comment]
I'm glad I could help.

**Comment by WUZHExl** [comment]
Hi IIrs, I'm sorry to bother you

When I once used RGCCA, I found that the AVE fraction value of a certain block was NA. 

What is the reason for this?

**Comment by llrs** [comment]
Hi,

In the released version of RGCCA there is no protection against `NA` values in the data matrices. There might be a `NA` in the data that propagated through RGCCA. In this case you would probably have `NA` as AVE inner and AVE outer. The `a` should also have at least one row with `NA` from the variable with the NA and the rest being filled normally with numeric values.

You can open an issue to the [official repository](https://github.com/rgcca-factory/RGCCA) or ask the developers there, they are very friendly and approachable.

**Comment by llrs** [comment]
I've seen you opened and issue there: https://github.com/rgcca-factory/RGCCA/issues/63. 

Do not forget that you need to provide context about the version, code and data used. The title of an issue is not the best place to ask a long question.
Providing enough information and context will make it easier to get a good answer.

**Comment by WUZHExl** [comment]
Thank you
